rng:
    build: rng
    ports:
      - "8001:80"

hasher:
    build: hasher
    ports:
      - "8002:80"

webui:
  build: webui
  extra_hosts:
    redis: 52.4.67.162
  ports:
    - "8000:80"
  volumes:
    - "webui/files/:/files/"
    
#redis:
#    image: redis

worker:
    build: worker
    extra_hosts:
        redis: 52.4.67.162
    links:
      - rng
      - hasher

